songs = ["Go Cyclones Go",
         "Fights!",
         "Rise Sons",
         "For I For S",
         "Fanfare",
         "Bells",
         "Armed Forces Fanface",
         "First Down",
         "Star Wars 2",
         "Star Wars 3",
         "Star Wars 4",
         "Mo Bamba",
         "Atchafalaya",
         "Fat Bottom Girls",
         "Juicy Wiggle",
         "Sweet Caroline",
         "Sucker",
         "Eat 'em up",
         "Third Down",
         "Cyclone Power",
         "Let's Go State",
         "Hero",
         "Happy Birthday",
         "Chorale Fights",
         "Game of Thrones",
         "Beer Barrel",
         "Boat",
         "Who Knows?",
         "Whatcha gonna do?",
         "Confident",
         "Wings",
         "Welper Wings!",
         "Singing Playing"]

cyclone_power = ["Take a shower?",
                 "Eiffel Tower?",
                 "Smell a flower?",
                 "Buy some flower?",
                 "Sweet and sour?",
                 "Eisenhower?",
                 "Protein powder?"]

responses = {"cool": "Ice Cold!",
             "go cyclones": "Yeah! Cyclones!",
             "we love the cyclones": "Yeah! Love!",
             "sense": "Dollars!",
             "dig": "With a shovel!",
             "super": "Super duper dad!",
             "boat": "Stroke!",
             "step show": "Cancelled.",
             "rise sons": "Starts with drums!",
             "hey band": "Hey what?",
             "tweet tweet tweet": "GO STATE",
             "lets go state": "Where are we going?",
             "let's go state": "Where are we going?",
             "cyclone!": "Power!",
             "thirsty": "Hydrate or diedrate!",
             "drink": "Hydrate or diedrate!",
             "clear": "Crystal!",
             "2": "Buh!",
             "two": "Buh!"
             }

valid_channels = [743519674456866927, 750839500233769069, 745852024398020659]