songs = ["Go Cyclones Go",
         "Fights!",
         "Rise Sons",
         "For I For S",
         "Fanfare",
         "Bells",
         "Armed Forces Fanface",
         "First Down",
         "Star Wars 2",
         "Star Wars 3",
         "Star Wars 4",
         "Mo Bamba",
         "Atchafalaya",
         "Fat Bottom Girls",
         "Juicy Wiggle",
         "Sweet Caroline",
         "Sucker",
         "Eat 'em up",
         "Third Down",
         "Cyclone Power",
         "Let's Go State",
         "Hero",
         "Happy Birthday",
         "Chorale Fights",
         "Game of Thrones",
         "Beer Barrel",
         "Boat",
         "Who Knows?",
         "Whatcha gonna do?",
         "Confident",
         "Wings",
         "Welper Wings!",
         "Singing Playing"]

cyclone_power = ["Take a shower?",
                 "Eiffel Tower?",
                 "Smell a flower?",
                 "Buy some flower?",
                 "Sweet and sour?",
                 "Eisenhower?",
                 "Protein powder?"]
